import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMultiCompanySchema1786010324138 implements MigrationInterface {
    name = 'InitialMultiCompanySchema1786010324138'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "erp_test"."companies" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "legal_name" character varying(255), "gstin" character varying(50), "address" text, "city" character varying(100), "state" character varying(100), "country" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."warehouses" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "code" character varying(50), "name" character varying(255) NOT NULL, "description" text, "address" text, "city" character varying(100), "state" character varying(100), "country" character varying(100), "pincode" character varying(20), "contact_person" character varying(255), "phone" character varying(20), "email" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_83a2f7c3947e29b4e04b6ccc76a" UNIQUE ("company_id", "code"), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."suppliers" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "supplier_code" character varying(100), "name" character varying(255) NOT NULL, "contact_person" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "gst_number" character varying(50), "address" text, "city" character varying(100), "state" character varying(100), "country" character varying(100), "pincode" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_847616e0ec0a0296a7a6bce1a21" UNIQUE ("company_id", "email"), CONSTRAINT "UQ_28e22bb0f3f325d692f57459267" UNIQUE ("company_id", "supplier_code"), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."items" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "sku" character varying(50), "name" character varying(255) NOT NULL, "purchase_rate" numeric(10,2) NOT NULL DEFAULT '0', "description" text, "unit" character varying(50), "reorder_level" integer DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_fb5aad8ce0eecfc55ffb727bd3a" UNIQUE ("company_id", "sku"), CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_213736582899b3599acaade2cd" ON "erp_test"."items" ("name") `);
        await queryRunner.query(`CREATE TABLE "erp_test"."stocks" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "item_name" character varying NOT NULL, "item_code" character varying NOT NULL, "warehouse_name" character varying(255) NOT NULL, "quantity" numeric(12,2) NOT NULL DEFAULT '0', "uom" character varying(20) NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "item_id" integer, CONSTRAINT "PK_b5b1ee4ac914767229337974575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."grn_items" ("id" SERIAL NOT NULL, "received_qty" integer NOT NULL, "qc_checked_qty" integer NOT NULL DEFAULT '0', "remarks" character varying(255), "grnId" integer, "itemId" integer, CONSTRAINT "PK_f6a5723d6cf2d0c66985fb833c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4642baa743e37bb4db908ff9e0" ON "erp_test"."grn_items" ("itemId") `);
        await queryRunner.query(`CREATE TABLE "erp_test"."purchase_order_items" ("id" SERIAL NOT NULL, "uom" character varying(50), "ordered_qty" numeric(10,3) NOT NULL, "unit_price" numeric(12,2) NOT NULL, "discount_percent" numeric(5,2) NOT NULL DEFAULT '0', "tax_percent" numeric(5,2) NOT NULL DEFAULT '0', "total_amount" numeric(12,2) NOT NULL, "purchase_order_id" integer, "item_id" integer, CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "erp_test"."purchase_orders_status_enum" AS ENUM('draft', 'sent', 'acknowledged', 'partial', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "erp_test"."purchase_orders" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "po_number" character varying(50) NOT NULL, "order_date" date NOT NULL, "expected_date" date, "status" "erp_test"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "terms_and_conditions" text, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "supplier_id" integer, "warehouse_id" integer, CONSTRAINT "UQ_d5a69bad90b4b215f39dc0672f7" UNIQUE ("company_id", "po_number"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."grns" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "grn_number" character varying(50) NOT NULL, "grn_date" date NOT NULL, "supplier_ref" character varying(100), "status" character varying(50) NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "warehouseId" integer, "purchaseOrderId" integer, CONSTRAINT "UQ_121117d098434f47ce650083056" UNIQUE ("company_id", "grn_number"), CONSTRAINT "PK_eef22b363aa66336dca8a5ce961" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."quality_check_items" ("id" SERIAL NOT NULL, "received_qty" integer NOT NULL, "checked_qty" integer NOT NULL, "passed_qty" integer NOT NULL, "failed_qty" integer NOT NULL, "remarks" text, "qualityCheckId" integer, "itemId" integer, CONSTRAINT "PK_63fe2d89f2735b6d70f7a5ca753" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "erp_test"."quality_checks_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "erp_test"."quality_checks" ("id" SERIAL NOT NULL, "qc_number" character varying NOT NULL, "qc_date" date NOT NULL, "inspector" character varying NOT NULL, "status" "erp_test"."quality_checks_status_enum" NOT NULL DEFAULT 'pending', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "grnId" integer, CONSTRAINT "UQ_15ae93cfc0f45d262b90af61b4e" UNIQUE ("qc_number"), CONSTRAINT "PK_f9d52a9f227cd4f72dc1eef4367" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."qc_items" ("id" SERIAL NOT NULL, "checked_qty" integer NOT NULL, "passed_qty" integer NOT NULL, "failed_qty" integer NOT NULL, "remarks" text, "qualityCheckId" integer, "grnItemId" integer, "itemId" integer, CONSTRAINT "PK_80af1189964bff5802b69d572ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."production_order_items" ("id" SERIAL NOT NULL, "production_order_id" integer NOT NULL, "item_id" integer NOT NULL, "required_qty" numeric(18,3) NOT NULL DEFAULT '0', "issued_qty" numeric(18,3) NOT NULL DEFAULT '0', "remarks" text, CONSTRAINT "PK_da269696b3b9e90fcce0a1dac6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."production_orders" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "order_number" character varying NOT NULL, "fg_item_id" integer NOT NULL, "quantity" numeric(18,3) NOT NULL DEFAULT '0', "warehouse_id" integer, "status" character varying(32) NOT NULL DEFAULT 'draft', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_70c1cb74a42f817a029f30dbf74" UNIQUE ("company_id", "order_number"), CONSTRAINT "PK_44d72e026027e3448b5d655e16e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "erp_test"."locations_location_type_enum" AS ENUM('area', 'rack', 'bin', 'floor', 'cold_storage', 'quarantine')`);
        await queryRunner.query(`CREATE TABLE "erp_test"."locations" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "location_code" character varying NOT NULL, "location_name" character varying NOT NULL, "description" text, "location_type" "erp_test"."locations_location_type_enum" NOT NULL DEFAULT 'rack', "capacity" numeric(15,3) NOT NULL DEFAULT '0', "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "warehouse_id" integer, "parent_location_id" integer, CONSTRAINT "UQ_6daf9517962a81f92b52145e0ba" UNIQUE ("company_id", "location_code"), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."stock_items" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "item_id" integer NOT NULL, "warehouse_id" integer NOT NULL, "quantity" numeric(18,3) NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d03ea7f1c52df96038c91b7f8eb" UNIQUE ("item_id", "warehouse_id"), CONSTRAINT "PK_52a266aa3e04b8ad1f01088f3f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."stock_ledger" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "item_id" integer NOT NULL, "warehouse_id" integer NOT NULL, "qty_in" numeric(18,3) NOT NULL DEFAULT '0', "qty_out" numeric(18,3) NOT NULL DEFAULT '0', "balance" numeric(18,3) NOT NULL DEFAULT '0', "reference_type" character varying, "reference_id" integer, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bb04575ee2ff52f72028f669701" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1bf26e3164bb46b8b7be287bb" ON "erp_test"."stock_ledger" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bbd5407875455ff7c4a594b841" ON "erp_test"."stock_ledger" ("item_id", "warehouse_id") `);
        await queryRunner.query(`CREATE TYPE "erp_test"."dispatch_orders_status_enum" AS ENUM('draft', 'dispatched', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "erp_test"."dispatch_orders" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "dispatch_number" character varying NOT NULL, "customer_name" character varying(255) NOT NULL, "dispatch_date" date NOT NULL, "status" "erp_test"."dispatch_orders_status_enum" NOT NULL DEFAULT 'draft', "total_value" numeric(12,2) NOT NULL DEFAULT '0', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_514cc69429ffae0ca672894c572" UNIQUE ("company_id", "dispatch_number"), CONSTRAINT "PK_b9a04f970539a3f2f67ba96bda0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "erp_test"."finished_goods_receipts_status_enum" AS ENUM('draft', 'confirmed')`);
        await queryRunner.query(`CREATE TABLE "erp_test"."finished_goods_receipts" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "receipt_number" character varying NOT NULL, "production_order_no" character varying(255) NOT NULL, "item_name" character varying(255) NOT NULL, "quantity" numeric(12,2) NOT NULL, "uom" character varying(50) NOT NULL, "warehouse_name" character varying(255) NOT NULL, "receipt_date" date NOT NULL, "status" "erp_test"."finished_goods_receipts_status_enum" NOT NULL DEFAULT 'draft', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_759baa179c824a3ded5f3126f46" UNIQUE ("company_id", "receipt_number"), CONSTRAINT "PK_bd4fbcec484a7fea7c3b998185f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."customers" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "customer_code" character varying(100), "name" character varying(255) NOT NULL, "contact_person" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "gst_number" character varying(50), "billing_address" text, "shipping_address" text, "city" character varying(100), "state" character varying(100), "country" character varying(100), "pincode" character varying(20), "credit_limit" numeric(14,2) NOT NULL DEFAULT '0', "payment_terms" character varying(50) NOT NULL DEFAULT 'Due on Receipt', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_946a7a5519eab49537ba6be271b" UNIQUE ("company_id", "email"), CONSTRAINT "UQ_3e47f55545cf7b43e6b920adcfc" UNIQUE ("company_id", "customer_code"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."permissions" ("id" SERIAL NOT NULL, "module" character varying(100) NOT NULL, "action" character varying(100) NOT NULL, "code" character varying(150) NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."roles" ("id" SERIAL NOT NULL, "company_id" integer, "name" character varying(100) NOT NULL, "description" character varying(255), "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_9acb61b0b5c438c8c68f6eb91a1" UNIQUE ("company_id", "name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."users" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "full_name" character varying, "role" character varying NOT NULL DEFAULT 'USER', "status" character varying NOT NULL DEFAULT 'ACTIVE', "refresh_token_hash" character varying(255), "last_login" TIMESTAMP, "created_by" integer, "updated_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "role_id" integer, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."bom_items" ("id" SERIAL NOT NULL, "bom_id" integer NOT NULL, "item_id" integer NOT NULL, "qty" numeric(18,3) NOT NULL DEFAULT '0', "uom" character varying(30), "remarks" text, CONSTRAINT "PK_f88a851d4f3c46533a354229e15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."boms" ("id" SERIAL NOT NULL, "company_id" integer NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(80), "description" text, "status" character varying(30) NOT NULL DEFAULT 'active', "fg_item_id" integer, "version" character varying(30) NOT NULL DEFAULT 'V1', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_59659fde3f22d3869fee0f78822" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "erp_test"."role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "erp_test"."role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "erp_test"."role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" ADD "company_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" DROP CONSTRAINT "UQ_15ae93cfc0f45d262b90af61b4e"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" ADD CONSTRAINT "UQ_83653a81959b03a1a80efd72c66" UNIQUE ("company_id", "qc_number")`);
        await queryRunner.query(`ALTER TABLE "erp_test"."warehouses" ADD CONSTRAINT "FK_3fcbfd5832b46945f514a7d1f56" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."suppliers" ADD CONSTRAINT "FK_6a9681499416e80c1ffac4fe86c" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."items" ADD CONSTRAINT "FK_88f394967ca01158e3b2ef9a054" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stocks" ADD CONSTRAINT "FK_31f27873d8f05a604f734926ff7" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stocks" ADD CONSTRAINT "FK_e31694209cc16bed37eee2b0e3e" FOREIGN KEY ("item_id") REFERENCES "erp_test"."items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grn_items" ADD CONSTRAINT "FK_106b209f935c117cb7f07af84c7" FOREIGN KEY ("grnId") REFERENCES "erp_test"."grns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grn_items" ADD CONSTRAINT "FK_4642baa743e37bb4db908ff9e06" FOREIGN KEY ("itemId") REFERENCES "erp_test"."items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "erp_test"."purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_order_items" ADD CONSTRAINT "FK_0b559d6b11abfb8956e45272110" FOREIGN KEY ("item_id") REFERENCES "erp_test"."items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_orders" ADD CONSTRAINT "FK_caed0f51e45442af8cea5c410b2" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "erp_test"."suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_orders" ADD CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e" FOREIGN KEY ("warehouse_id") REFERENCES "erp_test"."warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grns" ADD CONSTRAINT "FK_527097c5d05b297bee48b3392b0" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grns" ADD CONSTRAINT "FK_399cd8ffdd37d944ab8cc7a054b" FOREIGN KEY ("warehouseId") REFERENCES "erp_test"."warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grns" ADD CONSTRAINT "FK_65511a78156619867aa65d78dfa" FOREIGN KEY ("purchaseOrderId") REFERENCES "erp_test"."purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_check_items" ADD CONSTRAINT "FK_580d476ef191ec7c385d66171a5" FOREIGN KEY ("qualityCheckId") REFERENCES "erp_test"."quality_checks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_check_items" ADD CONSTRAINT "FK_ac9ad5be8ae0e197d5a1bff9a8b" FOREIGN KEY ("itemId") REFERENCES "erp_test"."items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" ADD CONSTRAINT "FK_0897c2610e5cc189cbb0324d236" FOREIGN KEY ("grnId") REFERENCES "erp_test"."grns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" ADD CONSTRAINT "FK_583a864b353339a4f2bc0315909" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."qc_items" ADD CONSTRAINT "FK_87b259e2fa19eed414a3dff3617" FOREIGN KEY ("qualityCheckId") REFERENCES "erp_test"."quality_checks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."qc_items" ADD CONSTRAINT "FK_6e6a422a1ba3a4d4abc818e4e7e" FOREIGN KEY ("grnItemId") REFERENCES "erp_test"."grn_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."qc_items" ADD CONSTRAINT "FK_0375f373c624d282f352c3c1fc6" FOREIGN KEY ("itemId") REFERENCES "erp_test"."items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."production_order_items" ADD CONSTRAINT "FK_37eb6f1ad7b081827657da783b1" FOREIGN KEY ("production_order_id") REFERENCES "erp_test"."production_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."production_orders" ADD CONSTRAINT "FK_a662afc877e2fae802a46927156" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."locations" ADD CONSTRAINT "FK_4f97374ec57955950cf6ab13326" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."locations" ADD CONSTRAINT "FK_381b76bcfaa0853f31db0d65dce" FOREIGN KEY ("warehouse_id") REFERENCES "erp_test"."warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."locations" ADD CONSTRAINT "FK_06f770dfdf4e78f67ad08f80cdc" FOREIGN KEY ("parent_location_id") REFERENCES "erp_test"."locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stock_items" ADD CONSTRAINT "FK_3d8526f36c53597e356832125ef" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stock_ledger" ADD CONSTRAINT "FK_d1bf26e3164bb46b8b7be287bb7" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."dispatch_orders" ADD CONSTRAINT "FK_7199e36dccfb00c090667cd8632" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."finished_goods_receipts" ADD CONSTRAINT "FK_d203fec588fa37a460dbb15d847" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."customers" ADD CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."roles" ADD CONSTRAINT "FK_4bc1204a05dde26383e3955b0a1" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."users" ADD CONSTRAINT "FK_7ae6334059289559722437bcc1c" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "erp_test"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."bom_items" ADD CONSTRAINT "FK_c982fd6310ed1543689a0208d94" FOREIGN KEY ("bom_id") REFERENCES "erp_test"."boms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."boms" ADD CONSTRAINT "FK_1e400d83cfface68080a4c4e6a0" FOREIGN KEY ("company_id") REFERENCES "erp_test"."companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "erp_test"."role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "erp_test"."roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "erp_test"."role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "erp_test"."permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "erp_test"."role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."boms" DROP CONSTRAINT "FK_1e400d83cfface68080a4c4e6a0"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."bom_items" DROP CONSTRAINT "FK_c982fd6310ed1543689a0208d94"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."users" DROP CONSTRAINT "FK_7ae6334059289559722437bcc1c"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."roles" DROP CONSTRAINT "FK_4bc1204a05dde26383e3955b0a1"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."customers" DROP CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."finished_goods_receipts" DROP CONSTRAINT "FK_d203fec588fa37a460dbb15d847"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."dispatch_orders" DROP CONSTRAINT "FK_7199e36dccfb00c090667cd8632"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stock_ledger" DROP CONSTRAINT "FK_d1bf26e3164bb46b8b7be287bb7"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stock_items" DROP CONSTRAINT "FK_3d8526f36c53597e356832125ef"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."locations" DROP CONSTRAINT "FK_06f770dfdf4e78f67ad08f80cdc"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."locations" DROP CONSTRAINT "FK_381b76bcfaa0853f31db0d65dce"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."locations" DROP CONSTRAINT "FK_4f97374ec57955950cf6ab13326"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."production_orders" DROP CONSTRAINT "FK_a662afc877e2fae802a46927156"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."production_order_items" DROP CONSTRAINT "FK_37eb6f1ad7b081827657da783b1"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."qc_items" DROP CONSTRAINT "FK_0375f373c624d282f352c3c1fc6"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."qc_items" DROP CONSTRAINT "FK_6e6a422a1ba3a4d4abc818e4e7e"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."qc_items" DROP CONSTRAINT "FK_87b259e2fa19eed414a3dff3617"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" DROP CONSTRAINT "FK_583a864b353339a4f2bc0315909"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" DROP CONSTRAINT "FK_0897c2610e5cc189cbb0324d236"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_check_items" DROP CONSTRAINT "FK_ac9ad5be8ae0e197d5a1bff9a8b"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_check_items" DROP CONSTRAINT "FK_580d476ef191ec7c385d66171a5"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grns" DROP CONSTRAINT "FK_65511a78156619867aa65d78dfa"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grns" DROP CONSTRAINT "FK_399cd8ffdd37d944ab8cc7a054b"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grns" DROP CONSTRAINT "FK_527097c5d05b297bee48b3392b0"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_orders" DROP CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_orders" DROP CONSTRAINT "FK_caed0f51e45442af8cea5c410b2"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_order_items" DROP CONSTRAINT "FK_0b559d6b11abfb8956e45272110"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grn_items" DROP CONSTRAINT "FK_4642baa743e37bb4db908ff9e06"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."grn_items" DROP CONSTRAINT "FK_106b209f935c117cb7f07af84c7"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stocks" DROP CONSTRAINT "FK_e31694209cc16bed37eee2b0e3e"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."stocks" DROP CONSTRAINT "FK_31f27873d8f05a604f734926ff7"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."items" DROP CONSTRAINT "FK_88f394967ca01158e3b2ef9a054"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."suppliers" DROP CONSTRAINT "FK_6a9681499416e80c1ffac4fe86c"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."warehouses" DROP CONSTRAINT "FK_3fcbfd5832b46945f514a7d1f56"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" DROP CONSTRAINT "UQ_83653a81959b03a1a80efd72c66"`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" ADD CONSTRAINT "UQ_15ae93cfc0f45d262b90af61b4e" UNIQUE ("qc_number")`);
        await queryRunner.query(`ALTER TABLE "erp_test"."quality_checks" DROP COLUMN "company_id"`);
        await queryRunner.query(`DROP INDEX "erp_test"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "erp_test"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "erp_test"."role_permissions"`);
        await queryRunner.query(`DROP TABLE "erp_test"."boms"`);
        await queryRunner.query(`DROP TABLE "erp_test"."bom_items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."users"`);
        await queryRunner.query(`DROP TABLE "erp_test"."roles"`);
        await queryRunner.query(`DROP TABLE "erp_test"."permissions"`);
        await queryRunner.query(`DROP TABLE "erp_test"."customers"`);
        await queryRunner.query(`DROP TABLE "erp_test"."finished_goods_receipts"`);
        await queryRunner.query(`DROP TYPE "erp_test"."finished_goods_receipts_status_enum"`);
        await queryRunner.query(`DROP TABLE "erp_test"."dispatch_orders"`);
        await queryRunner.query(`DROP TYPE "erp_test"."dispatch_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "erp_test"."IDX_bbd5407875455ff7c4a594b841"`);
        await queryRunner.query(`DROP INDEX "erp_test"."IDX_d1bf26e3164bb46b8b7be287bb"`);
        await queryRunner.query(`DROP TABLE "erp_test"."stock_ledger"`);
        await queryRunner.query(`DROP TABLE "erp_test"."stock_items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."locations"`);
        await queryRunner.query(`DROP TYPE "erp_test"."locations_location_type_enum"`);
        await queryRunner.query(`DROP TABLE "erp_test"."production_orders"`);
        await queryRunner.query(`DROP TABLE "erp_test"."production_order_items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."qc_items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."quality_checks"`);
        await queryRunner.query(`DROP TYPE "erp_test"."quality_checks_status_enum"`);
        await queryRunner.query(`DROP TABLE "erp_test"."quality_check_items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."grns"`);
        await queryRunner.query(`DROP TABLE "erp_test"."purchase_orders"`);
        await queryRunner.query(`DROP TYPE "erp_test"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "erp_test"."purchase_order_items"`);
        await queryRunner.query(`DROP INDEX "erp_test"."IDX_4642baa743e37bb4db908ff9e0"`);
        await queryRunner.query(`DROP TABLE "erp_test"."grn_items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."stocks"`);
        await queryRunner.query(`DROP INDEX "erp_test"."IDX_213736582899b3599acaade2cd"`);
        await queryRunner.query(`DROP TABLE "erp_test"."items"`);
        await queryRunner.query(`DROP TABLE "erp_test"."suppliers"`);
        await queryRunner.query(`DROP TABLE "erp_test"."warehouses"`);
        await queryRunner.query(`DROP TABLE "erp_test"."companies"`);
    }

}
